# Data Types in Python

This notebook is aimed at shedding some light on the different data types in Python. This shall form a strong foundation for your programming and Data Science journey.

## Numeric Data Type

You can check the data type of an object using the `type()` command.
The syntax looks like this: `type(variableName)`

### Your turn now.
Store the following into three different objects and check their data types:
* 2
* 1086J
* 3.14567

In [1]:
# Create an object with a value of 2
value_1 = 2

# Check the data type
type(value_1)

int

In [2]:
# Create an object with a value of 1086J
twixs = 1086J

# Check the data type
type(twixs)

complex

In [3]:
# Create an object with a value of 3.14567
skittles = 3.14567

# Check the data type
type(skittles)

float

## String Data Type

String Data type usually is used to store text. The data to be stored in this data type is enclosed between single ('') or double ("") quotes.
Recall that you printed your name in the previous Notebook. That was string data type.
Let's look at an example.

In [33]:
# Printing your name
My_Name = "JomaleeSmith"

# Check the results of the My_Name variable
My_Name

'JomaleeSmith'

In [ ]:
# Check the data type of the My_Name variable

You can combine string methods with print statements to request information from a user. This uses the `input` statement and gives users a blinking cursor to enter information.

Complex print statements are also possible where it prints string text, the contents of a variable, and even perform small operations in the statement and return the results. In the example below we will create a variable called `my_name` and use the input method to ask the user to input their name. From there we can print a statement saying hello, the user's entered name, and some punctuation. In the next print statement we can use the `type()` method to print the data type of the variable `my_name`.

In [7]:
# Your turn to play around now.
# Use the input statement to ask a user to enter their name
# Syntax looks like this: descriptiveVariableName = input("Question to be asked? ")
my_name = input("What is your name?")

# Your turn to play around now.
# Use the input statement to ask a user to enter their name
# Syntax looks like this: descriptiveVariableName = input("Question to be asked? ")
my_name = input("What is your name?")

# Use a print statement to check your input. Add a greeting to your statement.
# Syntax looks like this: print("Greeting", descriptiveVariableName, "!")
print("Hello,",my_name,"!")

# Now use a print statement to tell the user the data type.
# Syntax looks like this: print("Your name is a ",type(descriptiveVariableName))
print("Your name is a", type(my_name))
# Syntax looks like this: print("Your name is a ",type(descriptiveVariableName))
print("Your name is a", type(my_name))

What is your name?Jomale Smith
What is your name?Jomalee Smith
Hello, Jomalee Smith !
Your name is a <class 'str'>
Your name is a <class 'str'>

Various functions can be performed using strings like searching within a string, conversion to lowercase/uppercase, count, length, splitting, replacing, trimming, partitioning etc.

In [8]:
# Let's check how many characters does your name contain.
# Syntax: len(variableName)
print("Your name has", len(my_name),"characters.")

Your name has 13 characters.

In [9]:
# Let's see if My_Name is all Caps or not.
# isupper() returns True if all the letters are Capitals, False if atleast one letter in in lower case.
# Syntax: variableName.isupper()
print("Is your name all uppercase?", my_name.isupper())

Is your name all uppercase? False

In [10]:
# Let's convert My_Name to all caps.
# Syntax: variableName = variableName.upper()
my_name = my_name.upper()

# Call the variable using the variable name.
print("Your name in all caps is", my_name)

Your name in all caps is JOMALEE SMITH

In [11]:
# Check the uppercase again,
# Now the output of isupper() changes to True.
print("Is your name all uppercase now?", my_name.isupper())

Is your name all uppercase now? True

In [12]:
# Your turn to try it now.
# Write a sentence and store it into an object.
# Don't forget quotation marks for strings
new_sentence = "I love going to the store!"

# Use a print statement to view your new_sentence
print(new_sentence)
# Use the .upper() method in a print statement to print the upper case sentence
# HINT: Use a print statement, your variable name, and the .upper() method
print(new_sentence.upper())

# Use the .capitalize() method to print the sentence with the first word capitalized.
print(new_sentence.capitalize())

# Use the .title() method to print the sentence with the first letter of each word capitalized.
print(new_sentence.title())

I love going to the store!
I LOVE GOING TO THE STORE!
I love going to the store!
I Love Going To The Store!

In [13]:
# Check the data type of the object you just created.
print("The data type of new_sentence is", type(new_sentence))

The data type of new_sentence is <class 'str'>

In [14]:
# Check if it is all caps or not.
# Syntax: variableName.isupper()
print("Is the sentence all caps?", new_sentence.isupper())

Is the sentence all caps? False

In [15]:
# Challenge - Check if it is all lower case or not.
# Use the example above to complete the challenge question
print("Is the sentence all lower case?", new_sentence.isupper())

Is the sentence all lower case? False

In [20]:
# Challenge - Convert your object into all caps.
new_sentence = new_sentence.upper()
print(new_sentence)

I LOVE GOING TO THE STORE!

In [21]:
# Challenge - Convert your object into all lower case.
new_sentence_lower = new_sentence.lower()
print(new_sentence_lower)

i love going to the store!

## Boolean Data Type

The boolean data type has just two values, i.e., True or False.

In [22]:
# Create two variables, one with a value of True, one with a value of False
mango_isthebest = True
mango_istheworse = False

In [23]:
# Check the data type of your new variables
# HINT: you can check multiple items by separating the statements with a comma
print("The data type of mango_isthebest is" "The data type of mango_istheworse", type(mango_isthebest), type(mango_istheworse))

The data type of mango_isthebest isThe data type of mango_istheworse <class 'bool'> <class 'bool'>

## Data Type Conversions

As explained earlier, data should be stored in correct form so that it can be manipulated efficiently later.
Quite a lot of times, data is not stored correctly or it gets imported incorrectly.
In such cases, data needs to be converted to its correct type so that it can be optimally used in our analysis.
Thus, let's look at data type conversion exercises to get you comfortable with the process.

In [24]:
# Create an object containing an integer.
my_integer = 26

In [25]:
# Check the data type of your new object
print("The data type of my_integer is", type(my_integer))

The data type of my_integer is <class 'int'>

In [26]:
# You want to use the value 1 as text. So let's convert it.
# Syntax: variableName = str(variableName)
my_integer = str(my_integer)

In [27]:
# Check the data type of your new object again.
print("The data type of my_integer is", type(my_integer))

The data type of my_integer is <class 'str'>

In [28]:
# Exercise for you. Store the number 123456 as string.
milky_way = 123456
# Check the data type
print("The data type of milky_way is", type(milky_way))

The data type of milky_way is <class 'int'>

In [29]:
# Let's do the opposite now.
# Create a variable and assign a numeric value as a string
# HINT: Any value inside of quotes is a string
my_string = "29"
# Check the data type of your variable
print("The data type of my_string is", type(my_string))

The data type of my_string is <class 'str'>

In [30]:
# Let's learn to convert a string to an integer now.
# Syntax: variableName = int(variableName)
converted_integer = int(my_string)
# Check the data type
print ("The data type of converted_integer is", type(converted_integer))

The data type of converted_integer is <class 'int'>

In [31]:
# Let's convert a string to a float.
# Syntax: variableName = float(variableName)
converted_float = float(my_string)
# Check the data type
print("The data tpe of converted_float is", type(converted_float))

The data tpe of converted_float is <class 'float'>

Good job so far!
You can also try converting strings to boolean and vice versa.
You could also try conversions from integers to float and float to integer.

Python is an intuitive language, so by default it stores data into correct formats.
But very often we come across data being stored incorrectly especially while importing.